name: Gerencia de configuracao

on: pull_request

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Adicionar etapas para instalar dependências e fazer o build
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.
      - name: run install and build
        run: |
          npm install
          npm run build

      # Adicionar etapas para deploy no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          publish_dir: /
